### PR TITLE
Multiple fixes for more accurate distance calculations

### LINKED ISSUE #1: use fabs() instead of abs() in C code
I found error in your code. In file "main.c" on lines 42 and 52 you need to use use fabs() function instead of abs(). The code in current version always leads to one iteration tolerance, since abs() function is used for integers.

### PR DESCRIPTION
**Pull request by davidcrossey**
- fabs instead of abs for more iterations checking tolerance
- reevaluate cosine etc after lambda converenge
- handle antipodies / long distances with negative sigma

Fixes #1 and more

### CODE REVIEW

File: main.c [hunk 1]
```diff
@@ -7,6 +7,22 @@ struct Result{
     double value2;
 };
 
+typedef struct geom {
+    double sin_sigma, cos_sigma, sigma, sin_alpha, cos_sq_alpha, cos2sigma;
+} geom; 
+
+void calcgeo(geom *g, double lam, double u1, double u2) {
```
Comment (dariusarnold) [inline main.c:14]: I like the deduplication!

**Review by dariusarnold — APPROVED** [review]
